print("Truthy🎈")
print(bool(55))
print(bool(-55))
print(bool(-10))
print(bool(0.0))
print(bool(0))
print(bool(0.1))
print(bool("0"))
print(bool(" "))
print(bool(True))
print(bool("False"))
print(bool([False]))
print(bool([0]))

print("Falsy🎈")
print(bool([]))
print(bool(0))
print(bool(-0))
print(bool(0))
print(bool(None))
print(bool(0j))
